import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "./component/Navigation";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WFK 2025 x DIU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <NavigationBar />

        <main className="flex-1 flex flex-col">
          {children}
        </main>

        <footer className="w-full bg-gradient-to-r from-slate-800 via-slate-700 to-slate-800 text-white py-4 mt-auto">
          <div className="max-w-6xl mx-auto px-5 text-center text-sm sm:text-base font-medium">
            Developed by: <span className="text-yellow-300 font-semibold"> <Link href="https://uthsob.me">Uthsob</Link></span>
          </div>
        </footer>

      </body>
    </html>
  );
}
